### ISSUE TITLE
B2C Seamless Migration: First sign-in Attempt is Failing

### ISSUE THREAD

**Issue by smcneany** [azure-ad-b2c/user-migration#22]
We are experiencing what appears to be a race condition in B2C after following the seamless migration process outlined in https://github.com/azure-ad-b2c/user-migration/tree/master/seamless-account-migration. 

The first time a user logs in, they are successfully validated against the legacy IdP via a web service, their 'requires migration' flag is successfully flipped to 'false', and their password is successfully written to B2C. However, when they hit the step 'login-NonInteractive', it is not authenticating them correctly and shows the error message "Invalid username or password." If the same user attempts a second login, it works. 

Is it possible there is a race condition whereby the password is written to B2C in the AAD-UserWritePasswordUsingObjectId step, but it is not yet available to the login-NonInteractive step that does the authentication? If not, are there any other suggestions to look into?

**Comment by JasSuri** [comment]
Your problem is that the setup for the starter pack is incorrect. Specifically the part around registering the Proxy and IEF App registrations and then configuring the clientId+resource param in login-noninteractive.

You can automate the setup at https://aka.ms/iefsetup. Delete the Proxy and IEF app registrations before running. The tool will overwrite the policy files.

**Comment by blaataap** [comment]
Im using the seamless approach and everything seems to work but the actual login. I see the users migration flag is being updated from true to false but the login does not happen and im getting the "The username or password provided in the request are invalid.". Afterwards im not able to log in at all with the password that is valid and works for the old IDP. 
@JasSuri , i tried that link you sent but after logging in and giving permissions im getting a 404 on: https://b2ciefsetupapp.azurewebsites.net/Error

Any ideas?

**Comment by harrywynnwill** [comment]
Hey I am experiencing the same issue. I have been through and set the Proxy and IEF apps. The automated tool is not working for me.

**Comment by JasSuri** [comment]
Delete your Proxy and IEF apps, then try the [tool](https://aka.ms/iefsetup) again. Usually takes a few minutes to start working.

**Comment by maxschmittlaurin** [comment]
Hi ! I  am also experiencing this issue. <br><br>If the problem is an incorrect setup of the starter pack with the Proxy and IEF App registrations, how can the 'login-NonInteractive' step work when the user attempts a second login but not on the first login after the 'requires migration' flag is successfully flipped to 'false' and their password is written to B2C ? <br><br>I'm willing to try deleting the Proxy and IEF apps and use the tool that was linked, but I wonder how it will fix this particular issue.

**Comment by maxschmittlaurin** [comment]
I managed to fix the issue and it was indeed due to a misconfiguration in the login-NonInteractive technical profile. <br><br>In the InputClaims, I had `<InputClaim ClaimTypeReferenceId="grant_type" DefaultValue="password" />
            <InputClaim ClaimTypeReferenceId="scope" DefaultValue="openid" />` and I was missing the AlwaysUseDefaultValue="true" on both of these input claims. <br><br>I replaced these lines with `<InputClaim ClaimTypeReferenceId="grant_type" DefaultValue="password" AlwaysUseDefaultValue="true" />
            <InputClaim ClaimTypeReferenceId="scope" DefaultValue="openid" AlwaysUseDefaultValue="true" />` and the issue was gone.
