### ISSUE TITLE
JIT v2 missing step

### ISSUE THREAD

**Issue by danlopez** [azure-ad-b2c/user-migration#23]
As described, the JIT v2 flow does not work for legacy identity provider users logging in a second time. The first time a user with an account in the legacy directory authenticates, a user is created for them. The second time they authenticate, their login fails as the user already exists in B2C. One of two things should be changed: 
1. Ideally, there would be another step somewhere in the process (possibly at the start?) that checks if the username and password exist in AD B2C. If so, it would skip the migration process. _Note that this could lead to a weird issue if the user has already signed up in both places_
2. Alternatively, and this may be what this policy is expecting, the REST call in `REST-UserMigration-LocalAccount-SignIn` should be stateful, and track the migration state of the user, returning `null` after migration has been completed. This seems like it requires a separate callback from ADB2C to a new REST endpoint _after_ migration has been completed to be successful.

**Comment by JasSuri** [comment]
It was supposed to be intended to follow the second pattern, by deleting the user from the azure table
https://github.com/azure-ad-b2c/user-migration/blob/master/jit-migration-v2/source-code/AADB2C.JITUserMigration/Controllers/UserMigrationController.cs#L101

That should then return null.

I think this is a bug due to claimsEquals precondition, it won’t handle null. Null claim will make it evaluate to execute the validation technical profile.
https://github.com/azure-ad-b2c/user-migration/blob/master/jit-migration-v2/policy/TrustFrameworkExtensions.xml#L60

Adding a defaultValue here should solve this
https://github.com/azure-ad-b2c/user-migration/blob/master/jit-migration-v2/policy/TrustFrameworkExtensions.xml#L156

```xml
  <OutputClaim ClaimTypeReferenceId="needToMigrate" DefaultValue="null"/>
```
